# Generated by Django 6.0 on 2026-01-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_refactor_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrol',
            name='name',
            field=models.CharField(choices=[('DOVE', 'DOVE'), ('LIO', 'LIO'), ('CAT', 'CAT')], max_length=10, unique=True),
        ),
    ]
